#!/bin/sh

# dmenu_run improved
# command ending with '!', is started in the terminal.

cmd="$(dmenu_path | dmenu "$@")"

case $cmd in
    *\;) "${TERMINAL:-st}" -e "${cmd%?}" & ;;
    *)   "${cmd}" & ;;
esac
